name: Print Password

on: [push]

jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
    - name: Print Password
      env: 
        MY_PASSWORD: ${{ secrets.PASSWORD }}
      run: echo "My password => $MY_PASSWORD"
